name: BuildAndTestOnEveryPush.yml

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    name: Build on ubuntu
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: set up docker
      run: chmod 777 ./_build/deploy_oracle_docker_container.sh && ./_build/deploy_oracle_docker_container.sh

    - name: Build
      run: dotnet build
    
    - name: Test
      run: dotnet test
      
    - name: Pack release version of task
      run: dotnet pack --configuration Release --include-source
      
    - name: Push NuGet package to the testfeed
      run: dotnet nuget push Frends.Community.Oracle/bin/Release/Frends.Community.Oracle.*.nupkg  --api-key ${{ secrets.COMMUNITY_FEED_API_KEY }} --source https://www.myget.org/F/frends-community-test/api/v2/package